# When true (recommended), appends a cache-busting timestamp to the
# images referenced in the email.  This ensures the client always
# retrieves the latest version of the image and helpful during client
# previews.  Generally this should be disabled in production.
cache-bust: true

# When true copies image alt-text to the title property.  Populating both
# presents a more consistent image tooltip experience.
copy-alt-to-title: false

# When true (recommended), minifies the HTML and CSS of the email.  Should
# usually be disabled in development to make debugging easier.
minify: true

# When true (recommended), enables automatic image optimization of GIF,
# JPG and PNG images used in your email.
# https://inkcite.readme.io/v1.0/docs/image-optimization
optimize-images: true

# When empty links are found in content, this is the URL that will be
# included instead - so that clients understand this link is missing
# and needs to be provided.
missing-link-url: 'https://github.com/404'

# Add Google Fonts (https://www.google.com/fonts) to your emails.  Add
# the URLs to the family and sizes needed in your email.  Then reference
# the font family in either source.html:
#
#   {td font-family="'Open Sans Condensed', sans-serif"
#
# or inside of helpers.tsv:
#
#   default-font-family 'Open Sans Condensed', sans-serif
#
# https://inkcite.readme.io/docs/fonts#section-google-fonts
#
#fonts:
# - 'https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700'

# Inkcite can generate multiple versions of an email from a single source
# file which is useful for targeted mailings and a/b testing.  Specify a
# unique, single-word identifier for each version.
# https://dash.readme.io/project/inkcite/v1.0/docs/ab-testing-and-versioning
#
#versions:
#  - past_customer
#  - prospect

# SMTP settings for sending previews to the small list of internal and client
# addresses specified below.  Most importantly, specify the address your test
# emails will be sent 'from:'
# https://dash.readme.io/project/inkcite/v1.0/docs/email-previews
#
smtp:
  host: 'smtp.gmail.com'
  port: 587
  domain: 'yourdomain.com'
  username: ''
  password: ''
  from: 'Your Name <email@domain.com>'

# Mailgun settings for sending previews via their 3x faster API.  Sign up for
# a free account and retrieve your API key and sending domain from your
# Mailgun account dashboard.
# https://inkcite.readme.io/v1.0/docs/email-previews#section-sending-via-mailgun
#
# mailgun:
#  api-key: 'key-your-api-key'
#  domain: 'mg.sending-domain.com'
#  from: 'Your Name <email@domain.com>'

# Specify the distribution lists for preview versions of your email.
#
recipients:
  client:
    - 'Awesome Client <awesome.client@domain.com>'
  internal:
    - 'Creative Director <creative.director@domain.com>'
    - 'Proofreader <proof.reader@domain.com>'

# Easy Litmus integration for compatibility testing.
# https://inkcite.readme.io/docs/compatibility-testing
#
litmus:
  subdomain: ''
  username: ''
  password: ''

# Easy deployment of static assets to a CDN or publicly-accessible
# server - required when your email has images.
# https://dash.readme.io/project/inkcite/v1.0/docs/cdn-upload
#
sftp:
  host: ''
  path: ''
  username: ''
  password: ''

# Link tagging ensures that every link in the email includes a
# name-value pair.  This is useful if you harvest data from your
# website analytics.  {id} will be replaced with the unique ID
# from the link if you're concerned about which link the
# recipient clicked to get to your website.
# https://inkcite.readme.io/v1.0/docs/links
#
tag-links: "from_email=myemail|{id}"

# Optionally, if your email newsletter links to multiple websites
# and you only want to tag links to a specific domain, include
# that domain in this setting.
# https://inkcite.readme.io/v1.0/docs/links
#
#tag-links-domain: 'clientdomain.com'


# Environment-specific overrides allow you to change any setting
# for each environment (e.g local development vs. client preview).
# https://dash.readme.io/project/inkcite/v1.0/docs/environments

# These overrides apply to your local development environment when
# you are viewing the email in your browser via Inkcite's server.
development:
  minify: false

# These overrides apply to previews both internally and to external
# clients and sent with Inkcite's preview function.
preview:
  view-in-browser-url: 'http://preview.contenthost.com/path/{filename}'
  image-host: 'http://preview.imagehost.com/emails/'

# These overrides apply to the final, ready-to-send files.
production:
  cache-bust: false
  image-host: "http://production.imagehost.com/emails/myemail"
  view-in-browser-url: 'http://production.contenthost.com/path/{filename}'
